/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#131e0f",
        "surface-bright": "#eefdf0",
        "on-secondary-fixed-variant": "#4e453c",
        "inverse-primary": "#bccbb3",
        "tertiary-fixed": "#ffdbd1",
        "surface-container-high": "#ddecdf",
        "secondary-fixed": "#eee0d3",
        "inverse-surface": "#26332b",
        "on-surface": "#121e16",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "background": "#eefdf0",
        "on-secondary-fixed": "#211a12",
        "inverse-on-surface": "#e6f5e7",
        "on-secondary": "#ffffff",
        "tertiary": "#8b4e3b",
        "on-secondary-container": "#6b6157",
        "tertiary-container": "#cc846e",
        "surface-dim": "#cfded1",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "outline": "#757870",
        "surface": "#eefdf0",
        "surface-container-low": "#e8f8ea",
        "secondary-container": "#ebddd0",
        "on-surface-variant": "#444841",
        "on-primary-container": "#263221",
        "primary-container": "#8c9a84",
        "on-tertiary-container": "#512011",
        "on-primary-fixed-variant": "#3e4a38",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#d1c4b8",
        "surface-variant": "#d7e6d9",
        "tertiary-fixed-dim": "#ffb59f",
        "on-tertiary-fixed-variant": "#6f3726",
        "outline-variant": "#c5c8bf",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d7e6d9",
        "surface-container": "#e3f2e4",
        "primary-fixed-dim": "#bccbb3",
        "surface-tint": "#55624f",
        "on-background": "#121e16",
        "secondary": "#665d52",
        "primary-fixed": "#d8e7ce",
        "primary": "#55624f",
        "on-tertiary-fixed": "#380d02",
        "alabaster": "#F9F8F4",
        "forest": "#2D3A31",
        "sage": "#8C9A84",
        "clay": "#DCCFC2",
        "terracotta": "#C27B66",
        "brand-alabaster": "#F9F8F4",
        "brand-forest": "#2D3A31",
        "brand-sage": "#8C9A84",
        "brand-clay": "#DCCFC2",
        "brand-terra": "#C27B66",
        "brand-stone": "#E5E3D8",
        "sage-green": "#8C9A84",
        "terracotta": "#C27B66",
        "dark-green": "#2D3A31",
        "stone-border": "#E6E2DA",
        "soft-clay": "#DCCFC2",
        "prompt-bg": "#F9F8F4",
        "prompt-label": "#8C9A84",
        "prompt-headline": "#C27B66",
        "prompt-card-border": "#E6E2DA",
        "prompt-soft-clay": "#DCCFC2",
        "paper": "#F9F8F4",
        "line": "#E6E2DA",
        "dot": "#2D3A31",
        "card2": "#DCCFC2",
        "custom-bg": "#F9F8F4",
        "custom-label": "#8C9A84",
        "custom-headline": "#C27B66",
        "custom-circle": "#DCCFC2",
        "custom-forest": "#2D3A31"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "24px",
        "stagger-offset": "48px",
        "base": "8px",
        "section-gap": "120px",
        "gutter": "32px"
      },
      fontFamily: {
        "display-xl": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-2xl": ["Playfair Display", "serif"],
        "body-md": ["\"Source Sans 3\"", "sans-serif"],
        "body-lg": ["\"Source Sans 3\"", "sans-serif"],
        "label-caps": ["\"Source Sans 3\"", "sans-serif"],
        "emphasis": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"]
      },
      fontSize: {
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "display-2xl": ["96px", { lineHeight: "104px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "600" }]
      },
      animation: {
        'spin-slow': 'spin 12s linear infinite',
        'spin-slow-reverse': 'spin 15s linear infinite reverse',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        }
      }
    },
  },
  plugins: [],
}
